#!/bin/bash
#menu
clear
echo -e ""
echo -e ">> Menu SSH Websocket & OpenVPN "
echo -e ""
echo -e "1.       : Create SSH Websocket & OpenVPN ( usernew ) "
echo -e "2.       : Create Trial SSH Websocket & OpenVPN ( trial ) "
echo -e "3.       : Extend SSH and OpenVPN account Active Period ( renew )"
echo -e "4.       : Check Member SSH Websocket & OpenVPN ( member )"
echo -e "5.       : Check User Login SSH Websocket & OpenVPN ( cek ) "
echo -e "6.       : Delete SSH and OpenVPN accounts ( deluser }"
echo -e "7.       : Auto Delete Multi Login User ( autokick ) "
echo -e "8.       : Delete Expired SSH websocket & OpenVpn ( delete ) "
echo -e "9.       : Check Multi Login User SSH & OpenVPN ( checklim ) "
echo -e "10.     : Menu Restart All Service ( Restart )  
echo -e ""
echo -e ">> Menu V2ray / Vmess "
echo -e ""
echo -e "11.     : Create Account Vmess ( add-ws)"
echo -e "12.     : Delete Account Vmess ( del-ws )"
echo -e "13.     : Check User Login Vmess ( cek-ws )"
echo -e "14.     : Extend Account Vmess ( renew-vmess )"
echo -e "15.     : Generate Certv2ray ( cer-v2ray )"
echo -e ""
echo -e ">> Menu V2ray / Vless "
echo -e ""
echo -e "16.     : Create  Account Vless ( add-vless ) "
echo -e "17.     : Delete Acount Vless ( del-ws ) "
echo -e "18.     : Extend Acount Vless ( renew-vless )"
echo -e "19.     : Check User Login Vless ( cek-vless )"
echo -e ""
echo -e">> Menu TrojanGFW "
echo -e""


